# Generated by Django 4.0.5 on 2022-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='wondering',
            field=models.IntegerField(default=0),
        ),
    ]
